tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "keys-pub/tap"
tap "linux-noah/noah"
tap "neovim/neovim"
tap "nyuichi/satysfi"
tap "orf/brew"
tap "rhysd/tweet-app", "https://github.com/rhysd/tweet-app"
brew "cmake"
brew "docker", link: false
brew "ghostscript"
brew "expect"
brew "ghq"
brew "gibo"
brew "git"
brew "go"
brew "hub"
brew "hugo"
brew "knock"
brew "llvm"
brew "mas"
brew "neovim"
brew "nodebrew"
brew "octave"
brew "openjdk"
brew "peco"
brew "qemu"
brew "rbenv"
brew "ripgrep"
brew "ruby"
brew "tig"
brew "vim"
brew "wget"
brew "orf/brew/gping"
cask "discord"
cask "docker"
cask "mactex"
cask "skim"
cask "slack"
cask "thunderbird"
cask "visual-studio-code"
cask "dropbox"
cask "firefox"
cask "mathpix-snipping-tool"
cask "night-owl"
cask "protonvpn"
cask "skype"
cask "telegram-desktop"
cask "zoom"
mas "LINE", id: 539883307
mas "Pomodoro-Tracker", id: 1396146802
mas "Spark", id: 1176895641
mas "Tot", id: 1491071483
